# -*- coding: utf-8 -*-
"""
SQLHawk Report Generator
========================
Turns a list of Finding objects into a clean, client-ready HTML report:
severity badges, per-finding evidence, and remediation advice. This is
the artifact you actually hand to a site owner or attach to a bug
bounty submission.

Generated in English or Persian depending on the `lang` argument passed
to save_report() - matching whichever language the CLI session used.
Browsers implement full Unicode bidi + Arabic/Persian shaping natively,
so unlike the terminal, the Persian report needs no manual text fixing -
just `dir="rtl"` and `lang="fa"` on the page.
"""

from __future__ import annotations

import html
from datetime import datetime, timezone

from sqlhawk.injector.injector import Finding, SEVERITY_ORDER

SEVERITY_COLORS = {
    "Critical": "#b91c1c",
    "High": "#c2410c",
    "Medium": "#a16207",
    "Low": "#0f766e",
}

SEVERITY_LABELS = {
    "en": {"Critical": "Critical", "High": "High", "Medium": "Medium", "Low": "Low"},
    "fa": {"Critical": "بحرانی", "High": "بالا", "Medium": "متوسط", "Low": "پایین"},
}

STR = {
    "page_title": {"en": "SQLHawk Scan Report", "fa": "گزارش اسکن SQLHawk"},
    "target_label": {"en": "Target", "fa": "هدف"},
    "generated_label": {"en": "Generated", "fa": "تاریخ تولید"},
    "url_label": {"en": "URL/Endpoint", "fa": "آدرس/نقطه دسترسی"},
    "parameter_label": {"en": "Parameter", "fa": "پارامتر"},
    "method_label": {"en": "Method", "fa": "متد"},
    "db_label": {"en": "DB Engine", "fa": "نوع دیتابیس"},
    "evidence_label": {"en": "Evidence", "fa": "مدرک"},
    "fix_label": {"en": "Suggested fix", "fa": "راه‌حل پیشنهادی"},
    "no_findings": {
        "en": "No SQL injection indicators were detected with the current "
              "payload set. This does not guarantee the target is fully "
              "secure &mdash; consider deeper manual testing.",
        "fa": "هیچ نشانه‌ای از SQL Injection با مجموعه payload فعلی پیدا "
              "نشد. این به معنای امن بودن کامل هدف نیست &mdash; بررسی "
              "دستی عمیق‌تر توصیه می‌شود.",
    },
    "footer": {
        "en": "Generated by SQLHawk &mdash; for authorized security testing only.",
        "fa": "تولید شده توسط SQLHawk &mdash; فقط برای تست امنیتی مجاز.",
    },
}


def _s(key: str, lang: str) -> str:
    return STR[key].get(lang, STR[key]["en"])


_TEMPLATE = """<!DOCTYPE html>
<html lang="{lang}" dir="{dir}">
<head>
<meta charset="UTF-8">
<title>{page_title}</title>
<style>
  body {{ font-family: -apple-system, Segoe UI, Roboto, Tahoma, sans-serif; margin: 0; background: #0b1120; color: #e2e8f0; }}
  header {{ padding: 32px; background: #111827; border-bottom: 1px solid #1f2937; }}
  header h1 {{ margin: 0; font-size: 24px; }}
  header p {{ color: #94a3b8; margin: 6px 0 0; }}
  main {{ padding: 24px 32px; max-width: 980px; margin: 0 auto; }}
  .summary {{ display: flex; gap: 16px; margin-bottom: 24px; flex-wrap: wrap; }}
  .summary .card {{ background: #111827; border: 1px solid #1f2937; border-radius: 8px; padding: 16px 20px; min-width: 120px; }}
  .summary .card .num {{ font-size: 28px; font-weight: 700; }}
  .finding {{ background: #111827; border: 1px solid #1f2937; border-radius: 10px; padding: 20px; margin-bottom: 16px; }}
  .badge {{ display: inline-block; padding: 3px 10px; border-radius: 999px; font-size: 12px; font-weight: 700; color: white; }}
  .finding h3 {{ margin: 8px 0 4px; font-size: 16px; word-break: break-all; }}
  .meta {{ color: #94a3b8; font-size: 13px; margin-bottom: 10px; }}
  code, pre {{ background: #0b1120; border: 1px solid #1f2937; border-radius: 6px; padding: 8px 10px; display: block; overflow-x: auto; font-size: 13px; color: #fca5a5; direction: ltr; text-align: left; }}
  .remediation {{ margin-top: 10px; background: #052e2b; border: 1px solid #115e59; padding: 10px 12px; border-radius: 6px; font-size: 13px; color: #99f6e4; }}
  footer {{ text-align: center; color: #64748b; font-size: 12px; padding: 24px; }}
</style>
</head>
<body>
<header>
  <h1>{page_title}</h1>
  <p>{target_label}: {target} &nbsp;|&nbsp; {generated_label}: {generated_at}</p>
</header>
<main>
  <div class="summary">
    {summary_cards}
  </div>
  {findings_html}
  {no_findings}
</main>
<footer>
  {footer}
</footer>
</body>
</html>
"""

_FINDING_TEMPLATE = """
<div class="finding">
  <span class="badge" style="background:{color}">{severity}</span>
  <h3>{technique}</h3>
  <div class="meta">
    {url_label}: {url} &nbsp;|&nbsp; {parameter_label}: <b>{parameter}</b> &nbsp;|&nbsp; {method_label}: {method}
    {db_line}
  </div>
  <pre>{payload}</pre>
  <div class="meta">{evidence_label}: {evidence}</div>
  <div class="remediation"><b>{fix_label}:</b> {remediation}</div>
</div>
"""


def _card(label: str, count: int, color: str) -> str:
    return (f'<div class="card"><div class="num" style="color:{color}">'
            f'{count}</div><div>{label}</div></div>')


def generate_html_report(target: str, findings: list[Finding], lang: str = "en") -> str:
    labels = SEVERITY_LABELS.get(lang, SEVERITY_LABELS["en"])

    findings_sorted = sorted(
        findings, key=lambda f: SEVERITY_ORDER.get(f.severity, 0), reverse=True
    )

    counts = {"Critical": 0, "High": 0, "Medium": 0, "Low": 0}
    for f in findings_sorted:
        counts[f.severity] = counts.get(f.severity, 0) + 1

    summary_cards = "".join(
        _card(labels[sev], counts.get(sev, 0), SEVERITY_COLORS[sev])
        for sev in ("Critical", "High", "Medium", "Low")
    )

    findings_html = ""
    for f in findings_sorted:
        db_line = (f"| {_s('db_label', lang)}: <b>{html.escape(f.db_engine)}</b>"
                   if f.db_engine else "")
        findings_html += _FINDING_TEMPLATE.format(
            color=SEVERITY_COLORS.get(f.severity, "#334155"),
            severity=html.escape(labels.get(f.severity, f.severity)),
            technique=html.escape(f.technique),
            url_label=_s("url_label", lang),
            url=html.escape(f.url),
            parameter_label=_s("parameter_label", lang),
            parameter=html.escape(f.parameter),
            method_label=_s("method_label", lang),
            method=html.escape(f.method.upper()),
            db_line=db_line,
            payload=html.escape(f.payload),
            evidence_label=_s("evidence_label", lang),
            evidence=html.escape(f.evidence),
            fix_label=_s("fix_label", lang),
            remediation=html.escape(f.remediation),
        )

    no_findings = ""
    if not findings_sorted:
        no_findings = f'<div class="finding">{_s("no_findings", lang)}</div>'

    return _TEMPLATE.format(
        lang=lang,
        dir="rtl" if lang == "fa" else "ltr",
        page_title=_s("page_title", lang),
        target_label=_s("target_label", lang),
        target=html.escape(target),
        generated_label=_s("generated_label", lang),
        generated_at=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        summary_cards=summary_cards,
        findings_html=findings_html,
        no_findings=no_findings,
        footer=_s("footer", lang),
    )


def save_report(target: str, findings: list[Finding], output_path: str, lang: str = "en") -> None:
    html_content = generate_html_report(target, findings, lang=lang)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html_content)
